apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-review
      version: v1
  template:
    metadata:
      labels:
        app: express-review
        version: v1
    spec:
      containers:
        - name: express-review-container
          image: ryutaterada/k8s-express:1.2.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
              name: express-review
---
apiVersion: v1
kind: Service
metadata:
  name: express-review-service
spec:
  type: ClusterIP
  selector:
    app: express-review
  ports:
    - port: 80
      targetPort: 5000
      name: http
