apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-buy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-buy
      version: v1
  template:
    metadata:
      labels:
        app: express-buy
        version: v1
    spec:
      containers:
        - name: express-buy-container
          image: ryutaterada/k8s-express:1.1.9
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
          ports:
            - containerPort: 5000
              name: express-buy
---
apiVersion: v1
kind: Service
metadata:
  name: express-buy-service
spec:
  type: ClusterIP
  selector:
    app: express-buy
  ports:
    - port: 80
      targetPort: 5000
      name: http
