apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-workshop
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-workshop
      version: v1
  template:
    metadata:
      labels:
        app: express-workshop
        version: v1
    spec:
      containers:
        - name: express-workshop-container
          image: ryutaterada/k8s-express:1.1.9
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
          ports:
            - containerPort: 5000
              name: express-workshop
---
apiVersion: v1
kind: Service
metadata:
  name: express-workshop-service
  namespace: database
spec:
  type: ClusterIP
  selector:
    app: express-workshop
  ports:
    - port: 80
      targetPort: 5000
      name: http
