apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-ws
      version: v1
  template:
    metadata:
      labels:
        app: express-ws
        version: v1
    spec:
      containers:
        - name: express-ws-container
          image: ryutaterada/k8s-express:1.2.4
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
              name: express-ws
---
apiVersion: v1
kind: Service
metadata:
  name: express-ws-service
spec:
  type: ClusterIP
  selector:
    app: express-ws
  ports:
    - port: 80
      targetPort: 5000
      name: http
