apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: ryutaterada/k8s-mysql
          #image: mysql:5.6
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
          env:
            - name: MYSQL_USER
              value: user
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: tenshoku
          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/db
            - name: db-config
              mountPath: /etc/mysql/conf.d
              readOnly: true
            #- name: mysql-initdb
            #  mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
        - name: db-config
          configMap:
            name: db-config
            items:
              - key: charset.cnf
                path: charset.cnf
        #- name: mysql-initdb
        #  persistentVolumeClaim:
        #    claimName: mysql-initdb-pv-claim
